config/routes.rb
Rails.application.routes.draw do
  root 'rounds#index'
  resources :players
  resources :players

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :player
  belongs_to :round
end

app/models/player.rb
class Player < ApplicationRecord

    has_many :bets, dependent: :destroy
    # add bonus daily of $10000 to each player 
    def self.bonus
            all.each do |player|
                player.money += 10000
                player.save
            end
    end

end

app/models/round.rb
class Round < ApplicationRecord
    has_many :bets


    
    # choose color of bet and round randomly
    def self.roulette_color
        number_rand = rand(100)+1

        if number_rand < 3 
            return "verde"
        elsif number_rand >= 3 && number_rand <=51
            return "rojo"
        else 
            return "negro"
        end

    end 

    # calculates the player's bet
    def self.bet_player temp,money_user

        if money_user > 0 && money_user<= 1000
            return money_user
        else
            if temp < 27
                return rand(8..15)*money_user/100
            else 
                return rand(3..7)*money_user/100
            end
        end

    end

    # check if the player won the round, and how much
    def self.check_bet color_player, color_round, amount

        if color_player != color_round
            return 0
        else
            if color_player == "rojo" || color_player == "negro"
                return amount*2
            else 
                return amount*15
            end 
        end 
        
    end

    # create a new round, it is the main function 
    def self.new_round
        players = Player.where("money > ?", 0)
        
        #check if there are players to make a round
        if players.length != 0

            round = Round.create(color:roulette_color()  ,temp:Weather.forecast_weather)
            round.save

            players.each do |player|
                user_color = roulette_color()
                amount_bet = bet_player(round.temp,player.money)
                gain_user  = check_bet(user_color,round.color,amount_bet)

                #check if the player has money to play
                if amount_bet != 0 
                    bet = Bet.create(
                            amount:amount_bet, 
                            color: user_color , 
                            gain:gain_user,
                            round_id:round.id, 
                            player_id:player.id,
                            player_balance:player.money
                        )
                    bet.save

                    # check if the player won
                    if !gain_user 
                        player.money = (player.money - amount_bet)
                    else
                        player.money += (check_bet(round.color, bet.color, bet.amount) - amount_bet)
                    end
                    player.save

                end
            end
        end
    end

end

app/models/weather.rb
class Weather < ApplicationRecord

    require "openssl"
    require 'net/http'
    require 'json'

    # Connection with WeatherUnclock API
    def self.get_forecast
        # Get the date to make the request
        date_today= Time.now.in_time_zone('Santiago').to_date
        date = (date_today +7).strftime("%Y-%m-%d")
        
        uri = URI("http://api.worldweatheronline.com/premium/v1/weather.ashx?q=Santiago&key=3a21433208bb459b83b140805182111&num_of_days=1&date=#{date}&format=json")
        res = Net::HTTP.get_response(uri)
        weather = res.body if res.is_a?(Net::HTTPSuccess)
        weather =JSON.parse(weather).with_indifferent_access

        temp = weather[:data][:weather][0][:maxtempC].to_f
        Weather.create(temp: temp)

        temp.to_i
    end

    #check if you have the forecast
    def self.forecast_weather

        date_today= Time.now.in_time_zone('Santiago').to_date.strftime("%Y.%m.%d")
        weather = Weather.last
        puts weather
        #cheked that there are records
        if weather

            #check if you already have that data
            if (weather.created_at.strftime("%Y.%m.%d") == date_today)               
                return weather.temp.to_i  
            else   
                return get_forecast
            end

        else    
            return get_forecast
        end
            
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    #Variables for handling classes of the navbar
    @round_class =""
    @player_class = "active"
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player_bets = Bet.where(player_id: @player.id).paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  # GET /players/new
  def new
    @player = Player.new
    @name_button = "Agregar"
  end

  # GET /players/1/edit
  def edit
    
    @name_button = "Editar"
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.money = 10000

      if @player.save
          redirect_to @player, notice: 'Jugador creado exitosamente.'
      else
          render :new 
      end
    
  end

  
  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    
      if @player.update(player_params)
        redirect_to @player, notice: 'Jugador fue modificado exitosamete.'
      else
        render :edit 
      end

  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy

     redirect_to players_url, notice: 'Jugador fue eliminado.' 


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :money)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  
  def index
    #Variables for handling classes of the navbar
    @round_class ="active"
    @player_class = ""

    @rounds = Round.paginate(:page => params[:page], :per_page => 15).all.order(created_at: :desc)

    #query of tables players and bets for main view
    @bets_of_plyers = Player.joins("INNER JOIN bets ON bets.player_id = players.id")
                            .select("bets.round_id,  
                                     players.id, 
                                     players.name, 
                                     bets.gain, 
                                     bets.amount, 
                                     bets.color, 
                                     bets.round_id")
                             .order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RouletteGame2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%=@round_class%>" id="rounds_li_nav">
        <%= link_to 'Rondas', {controller: "rounds", action:"index"}, {class:"nav-link", id:"rounds_nav"} %>
      </li>
      <li class="nav-item <%=@player_class%>" id="rounds_li_nav">
        <%= link_to 'Jugadores', {controller: "players", action:"index"}, {class:"nav-link", id:"players_nav"} %>
      </li>
    </ul>
    <span class="navbar-text">
      Juego de la ruleta Nnodes
    </span>
  </div>
</nav>
  <div class="container">
    <%= yield %>
    <div>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>
  <% if params[:action]=="edit" %>
      <div class="field form-group">
        <%= form.label :money %>
        <%= form.text_field :money, class:"form-control" %>
      </div>
  <% end%>
  <div class="actions">
    
    <%= form.submit @name_button, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="Title">
  <h1>Editando Jugador</h1>
</div>

<%= render 'form', player: @player%>

<%= link_to 'Ver', @player %> |
<%= link_to 'Volver', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="Title">Jugadores</h1>



<div class="player_table">
  <%= link_to 'Agregar nuevo', new_player_path, class: "btn btn-primary" %>
<% if @players.length != 0%>
    <table class="table table-bordered">
      <thead >
        <tr  class="bg-primary header_player_table">
          <th>Nombre</th>
          <th>Saldo</th>
          <th colspan="3">Actiones</th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.name %></td>
            <td>$<%= player.money.to_i %></td>
            <td><%= link_to 'Ver', player %></td>
            <td><%= link_to 'Editar', edit_player_path(player) %></td>
            <td><%= link_to 'Eliminar', player, method: :delete, data: { confirm: 'Are you sure?' }  %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
  <p>No existen jugadores registrados</p>
<% end %>

</div>

<br>

app/views/players/new.html.erb
<p id="notice"><%= notice %></p>

<h1 class="Title">Nuevo Jugador</h1>

<%= render 'form', player: @player %>

<%= link_to 'Volver', players_path, class: "btn btn-primary btn-new-player"%>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<div class="Title">
  <h1>Jugador <%= @player.name %></h1>
</div>

<p>MONTO TOTAL: $<%= @player.money.to_i %></p>

<%= link_to 'Volver', {controller:'players'}, {class:'btn btn-primary btn-show-player'} %>

<% if @player_bets.length.to_i != 0 %>
  <div class="player_table">
    <table class="table table-bordered">
        <thead class="bg-primary header_player_table">
            <tr>
              <th>#</th>
              <th>Fecha </th>
              <th>Hora</th>
              <th>Apuesta</th>
              <th>Color</th>
              <th>Ganancia</th>
              <th>Resultado</th>
              <th>Dinero</th>
            </tr>
        </thead>
        <tbody>

            <% @player_bets.each.with_index do |bet,index| %>
              <tr class="round_td">
                <td><%=@player_bets.length-index%></td>
                <td><%=bet.created_at.strftime("%Y-%m-%d")%></td>
                <td><%="#{bet.created_at.strftime("%H").to_i - 3}:#{bet.created_at.strftime("%M")}"%></td>
                <td>$<%=bet.amount%></td>
                <td><%=bet.color%></td>
                <td>$<%=bet.gain%></td>
                <td><%=bet.gain == 0 ? "Perdió" : "Ganó"%></td>
                <td>$<%=bet.player_balance.to_i%></td>
              </tr>
            <% end %>
            
        </tbody>
    </table>
  </div>

  <%# page buttons %>
  <div class="container_pagination">
    <%= will_paginate @player_bets %>
  </div>
<% else %>
  <p>Este Jugador no ha realizado apuestas</p>
<% end %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>
<div class="Title">
  <h1>Rondas</h1>
</div>



<div id="accordion">
<% @rounds.each do |round| %>
  <div class="card">
    <div class="card-header" id="heading<%=round.id%>"  data-toggle="collapse" data-target="#collapse<%=round.id%>"  aria-controls="collapse<%=round.id%>">
      <h5 class="mb-0">
        <button class="btn btn-link">
           <div class="text_card_round"><strong><%= "Ronda #{round.id }"%></strong></div>   
           <div class="text_card_round"><%="Fecha: #{round.created_at.strftime(" %d %b %Y")}"%> </div>  
           <div class="text_card_round"><%="Hora: #{round.created_at.strftime("%H").to_i - 3}:#{round.created_at.strftime("%M")}"%> </div> 
           <div class="text_card_round"><%="Temperatura: #{round.temp.to_i}ºC"%></div>
           <div class="round_img_color">
            <%= image_tag("#{round.color}.png", :alt => "rss feed", :class => "Img_color") %>
           </div> 
        </button>
      </h5>
    </div>

    <div id="collapse<%=round.id%>" class="collapse" aria-labelledby="heading<%=round.id%>" data-parent="#accordion">
      <div class="card-body">


              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apuesta</th>
                    <th scope="col">Color</th>
                    <th scope="col">Ganancia</th>
                    <th scope="col">Resultado</th>
                  </tr>
                </thead>
                <tbody>
                <% @bets_of_plyers.each do |bet_player| %>
                  
                  <% if bet_player.round_id == round.id%>
                    <tr>
                      <th scope="row">#</th>
                      <td><%= bet_player.name %></td>
                      <td><%= bet_player.amount %></td>
                      <td><%= image_tag("#{bet_player.color}.png", :alt => "rss feed", :class => "Img_color") %></td>
                      <td><%= bet_player.gain%></td>
                      <td><%= bet_player.gain == 0 ? "Perdió" : "Ganó"%></td>
                    </tr>
                  <% end %>
                <% end %>
                </tbody>
              </table>

      </div>
    </div>
  </div>
  <% end %>
</div>
<%# page buttons %>
<div class="container_pagination">
  <%= will_paginate @rounds %>
</div>